import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

type Gift = { id:string; name:string; description:string|null; price:number|null; image_url:string|null; product_url:string|null; status:string }
type Wedding = { id:string|null; partner_one:string; partner_two:string; wedding_date:string|null; description:string|null; location?:string; pix?:string; monogram?:string }
const personalizedWedding:Wedding={id:null,partner_one:'Lucas',partner_two:'Gabriella',wedding_date:'2028-01-09',description:'Oi! Estamos muito felizes em viver esse momento tão especial e queremos muito celebrar nosso casamento com você.',location:'Milícia da Imaculada · São Bernardo do Campo',pix:'11933201483',monogram:'LL + GV'}
function formatDate(value:string|null){if(!value)return null;return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`))}

export default async function WeddingPage({params}:PageProps<'/casamento/[slug]'>){
  const {slug}=await params
  let wedding:Wedding|null=slug==='lucas-e-gabriella'?personalizedWedding:null
  let gifts:Gift[]=[]
  if(!wedding){const supabase=await createClient();const {data}=await supabase.from('weddings').select('id, partner_one, partner_two, wedding_date, description').eq('slug',slug).maybeSingle();wedding=data;if(wedding?.id){const result=await supabase.from('gifts').select('id, name, description, price, image_url, product_url, status').eq('wedding_id',wedding.id).order('created_at',{ascending:false});gifts=(result.data as Gift[]|null)??[]}}
  else if(slug==='lucas-e-gabriella'){const supabase=await createClient();const {data}=await supabase.from('weddings').select('id, partner_one, partner_two, wedding_date, description').eq('slug',slug).maybeSingle();if(data){wedding={...personalizedWedding,...data};const result=await supabase.from('gifts').select('id, name, description, price, image_url, product_url, status').eq('wedding_id',data.id).order('created_at',{ascending:false});gifts=(result.data as Gift[]|null)??[]}}
  if(!wedding)notFound()
  const date=formatDate(wedding.wedding_date)
  return <main className="wedding-page"><header className="wedding-hero"><div className="wedding-monogram">{wedding.monogram??<>{wedding.partner_one.charAt(0)} <i>&</i> {wedding.partner_two.charAt(0)}</>}</div><span className="wedding-kicker">Com alegria, convidamos você a celebrar</span><h1>{wedding.partner_one} <em>&</em> {wedding.partner_two}</h1>{date&&<p className="wedding-date">{date}</p>}{wedding.location&&<p className="wedding-location">⌖ {wedding.location}</p>}<div className="invite-rule"><span>✦</span></div>{wedding.description&&<blockquote>“{wedding.description}”</blockquote>}<a href="#presentes" className="button button-light">Ver lista de presentes ↓</a></header>
    <section id="presentes" className="gift-section"><div className="section-heading"><span className="eyebrow">Escolhidos com carinho</span><h2>Nossa lista de presentes</h2><p>Sua presença já é o nosso maior presente. Se quiser nos mimar, reunimos aqui algumas ideias.</p></div>
      {!gifts?.length?<div className="empty-gifts">♡<h3>Estamos preparando tudo</h3><p>Nossa lista de presentes será divulgada em breve.</p></div>:<div className="gift-grid">{(gifts as Gift[]).map(gift=><article className="gift-card" key={gift.id}><div className="gift-image">{gift.image_url?<img src={gift.image_url} alt={gift.name}/>:<span>♢</span>}</div><div className="gift-content"><div className="gift-title-row"><h3>{gift.name}</h3><span className="status-pill">{gift.status==='available'?'Disponível':gift.status==='reserved'?'Reservado':'Presenteado'}</span></div>{gift.description&&<p>{gift.description}</p>}{gift.price!==null&&<strong>{Number(gift.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong>}{gift.product_url&&gift.status==='available'&&<a className="primary-action" href={gift.product_url} target="_blank" rel="noreferrer">Presentear o casal</a>}</div></article>)}</div>}
      {wedding.pix&&<div className="pix-card"><span className="pix-icon">◇</span><div><span className="app-kicker">Presente via Pix</span><h3>Prefere contribuir de outra forma?</h3><p>Qualquer valor será recebido com muito carinho.</p></div><div className="pix-key"><small>Chave Pix · celular</small><strong>(11) 93320-1483</strong></div></div>}
    </section><footer className="wedding-footer"><span>♡</span><p>Obrigado por fazer parte da nossa história.</p><small>Lucas & Gabriella · VowList</small></footer></main>
}
