create extension if not exists pgcrypto;
create table if not exists public.rsvps(id uuid primary key default gen_random_uuid(),wedding_id uuid not null references public.weddings(id) on delete cascade,guest_name text not null,phone text not null,attending boolean not null,companions integer not null default 0 check(companions between 0 and 10),created_at timestamptz not null default now());
create table if not exists public.gift_reservations(id uuid primary key default gen_random_uuid(),gift_id uuid not null unique references public.gifts(id) on delete cascade,wedding_id uuid not null references public.weddings(id) on delete cascade,guest_name text not null,guest_phone text not null,created_at timestamptz not null default now());
alter table public.rsvps enable row level security;alter table public.gift_reservations enable row level security;
create policy "public can confirm attendance" on public.rsvps for insert to anon,authenticated with check(exists(select 1 from public.weddings w where w.id=wedding_id));
create policy "owners can view confirmations" on public.rsvps for select to authenticated using(exists(select 1 from public.weddings w where w.id=wedding_id and w.owner_id=auth.uid()));
create policy "owners can view reservations" on public.gift_reservations for select to authenticated using(exists(select 1 from public.weddings w where w.id=wedding_id and w.owner_id=auth.uid()));
create or replace function public.reserve_gift(p_gift_id uuid,p_guest_name text,p_guest_phone text) returns text language plpgsql security definer set search_path=public as $$ declare v_wedding_id uuid;v_product_url text;begin if length(trim(p_guest_name))<2 or length(trim(p_guest_phone))<8 then raise exception 'Informe nome e telefone válidos.';end if;update public.gifts set status='reserved' where id=p_gift_id and status='available' returning wedding_id,product_url into v_wedding_id,v_product_url;if v_wedding_id is null then return null;end if;insert into public.gift_reservations(gift_id,wedding_id,guest_name,guest_phone) values(p_gift_id,v_wedding_id,trim(p_guest_name),trim(p_guest_phone));return coalesce(v_product_url,'reserved');end;$$;
grant execute on function public.reserve_gift(uuid,text,text) to anon,authenticated;
